version: '3'
services:
    api:
        build:
            context: .
            target: api
        ports:
            - 50000:50000
        environment:
            TZ: Asia/Tokyo
        command: >
            bash -c "/home/bin/api"
